using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CallCenter.Data.Migrations
{
    /// <inheritdoc />
    public partial class AuditLogsPartitioning : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. FK'lari kaldir (partitioned tabloda FK desteklenmiyor)
            migrationBuilder.DropForeignKey(
                name: "FK_AuditLogs_Customers_CustomerId",
                table: "AuditLogs");

            migrationBuilder.DropForeignKey(
                name: "FK_AuditLogs_Users_UserId",
                table: "AuditLogs");

            // 2. Mevcut tabloyu gecici olarak yeniden adlandir
            migrationBuilder.Sql("ALTER TABLE \"AuditLogs\" RENAME TO \"AuditLogs_old\";");

            // 3. Index'leri drop et (eski tabloda kaldigi icin)
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_AuditLogs_Category\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_AuditLogs_CreatedAt\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_AuditLogs_CustomerId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_AuditLogs_EntityType_EntityId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_AuditLogs_UserId\";");

            // 4. Partitioned tablo olustur (aylik, CreatedAt'e gore)
            migrationBuilder.Sql("""
                CREATE TABLE "AuditLogs" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "Category" character varying(50) NOT NULL,
                    "Action" character varying(50) NOT NULL,
                    "UserId" integer,
                    "UserName" character varying(100),
                    "EntityType" character varying(100),
                    "EntityId" character varying(50),
                    "Description" character varying(1000) NOT NULL,
                    "OldValues" text,
                    "NewValues" text,
                    "IpAddress" character varying(50),
                    "UserAgent" character varying(500),
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "CustomerId" integer,
                    PRIMARY KEY ("Id", "CreatedAt")
                ) PARTITION BY RANGE ("CreatedAt");
                """);

            // 5. Index'leri yeniden olustur (partitioned tabloda her partition'a otomatik uygulanir)
            migrationBuilder.Sql("""
                CREATE INDEX "IX_AuditLogs_Category" ON "AuditLogs" ("Category");
                CREATE INDEX "IX_AuditLogs_CreatedAt" ON "AuditLogs" ("CreatedAt");
                CREATE INDEX "IX_AuditLogs_CustomerId" ON "AuditLogs" ("CustomerId");
                CREATE INDEX "IX_AuditLogs_EntityType_EntityId" ON "AuditLogs" ("EntityType", "EntityId");
                CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
                """);

            // 6. Ilk partition'lar: mevcut ay + gelecek 3 ay + default
            migrationBuilder.Sql("""
                -- Default partition (range disindaki veriler buraya duser)
                CREATE TABLE "AuditLogs_default" PARTITION OF "AuditLogs" DEFAULT;

                -- 2026 partitions
                CREATE TABLE "AuditLogs_2026_01" PARTITION OF "AuditLogs"
                    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
                CREATE TABLE "AuditLogs_2026_02" PARTITION OF "AuditLogs"
                    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
                CREATE TABLE "AuditLogs_2026_03" PARTITION OF "AuditLogs"
                    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
                CREATE TABLE "AuditLogs_2026_04" PARTITION OF "AuditLogs"
                    FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
                CREATE TABLE "AuditLogs_2026_05" PARTITION OF "AuditLogs"
                    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
                CREATE TABLE "AuditLogs_2026_06" PARTITION OF "AuditLogs"
                    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
                """);

            // 7. Mevcut verileri tasi (varsa)
            migrationBuilder.Sql("""
                INSERT INTO "AuditLogs" SELECT * FROM "AuditLogs_old";
                """);

            // 8. Eski tabloyu sil
            migrationBuilder.Sql("DROP TABLE \"AuditLogs_old\";");

            // 9. Otomatik partition olusturma fonksiyonu
            // Her ay cagirildiginda gelecek 3 ayin partition'larini olusturur
            migrationBuilder.Sql("""
                CREATE OR REPLACE FUNCTION create_audit_partitions(months_ahead integer DEFAULT 3)
                RETURNS void AS $$
                DECLARE
                    partition_date date;
                    partition_name text;
                    start_date date;
                    end_date date;
                BEGIN
                    FOR i IN 0..months_ahead LOOP
                        partition_date := date_trunc('month', CURRENT_DATE + (i || ' months')::interval);
                        partition_name := 'AuditLogs_' || to_char(partition_date, 'YYYY_MM');
                        start_date := partition_date;
                        end_date := partition_date + interval '1 month';

                        -- Partition zaten var mi kontrol et
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_class WHERE relname = partition_name
                        ) THEN
                            EXECUTE format(
                                'CREATE TABLE %I PARTITION OF "AuditLogs" FOR VALUES FROM (%L) TO (%L)',
                                partition_name, start_date, end_date
                            );
                            RAISE NOTICE 'Partition olusturuldu: %', partition_name;
                        END IF;
                    END LOOP;
                END;
                $$ LANGUAGE plpgsql;
                """);

            // 10. KVKK 3 yil saklama suresi dolmus partition'lari silen fonksiyon
            migrationBuilder.Sql("""
                CREATE OR REPLACE FUNCTION drop_old_audit_partitions(retention_months integer DEFAULT 36)
                RETURNS void AS $$
                DECLARE
                    partition_rec record;
                    cutoff_date date;
                    partition_date date;
                BEGIN
                    cutoff_date := date_trunc('month', CURRENT_DATE - (retention_months || ' months')::interval);

                    FOR partition_rec IN
                        SELECT inhrelid::regclass::text AS partition_name
                        FROM pg_inherits
                        WHERE inhparent = '"AuditLogs"'::regclass
                        AND inhrelid::regclass::text != '"AuditLogs_default"'
                    LOOP
                        -- Partition adindan tarihi cikar (AuditLogs_YYYY_MM)
                        BEGIN
                            partition_date := to_date(
                                replace(replace(partition_rec.partition_name, '"AuditLogs_', ''), '"', ''),
                                'YYYY_MM'
                            );

                            IF partition_date < cutoff_date THEN
                                EXECUTE format('DROP TABLE IF EXISTS %s', partition_rec.partition_name);
                                RAISE NOTICE 'Eski partition silindi: % (cutoff: %)', partition_rec.partition_name, cutoff_date;
                            END IF;
                        EXCEPTION WHEN OTHERS THEN
                            -- Default veya bozuk isimli partition'lari atla
                            CONTINUE;
                        END;
                    END LOOP;
                END;
                $$ LANGUAGE plpgsql;
                """);

            // 11. Bakim fonksiyonu — tek cagriyla hem yeni olustur hem eskiyi sil
            migrationBuilder.Sql("""
                CREATE OR REPLACE FUNCTION maintain_audit_partitions()
                RETURNS void AS $$
                BEGIN
                    -- Gelecek 3 ayin partition'larini olustur
                    PERFORM create_audit_partitions(3);
                    -- 36 aydan (3 yil) eski partition'lari sil
                    PERFORM drop_old_audit_partitions(36);
                END;
                $$ LANGUAGE plpgsql;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Fonksiyonlari sil
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS maintain_audit_partitions();");
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS drop_old_audit_partitions(integer);");
            migrationBuilder.Sql("DROP FUNCTION IF EXISTS create_audit_partitions(integer);");

            // Partitioned tabloyu sil (tum partition'larla birlikte)
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"AuditLogs\" CASCADE;");

            // Normal tablo olarak yeniden olustur
            migrationBuilder.Sql("""
                CREATE TABLE "AuditLogs" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "Category" character varying(50) NOT NULL,
                    "Action" character varying(50) NOT NULL,
                    "UserId" integer,
                    "UserName" character varying(100),
                    "EntityType" character varying(100),
                    "EntityId" character varying(50),
                    "Description" character varying(1000) NOT NULL,
                    "OldValues" text,
                    "NewValues" text,
                    "IpAddress" character varying(50),
                    "UserAgent" character varying(500),
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "CustomerId" integer,
                    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
                );
                """);

            // Index'leri geri olustur
            migrationBuilder.Sql("""
                CREATE INDEX "IX_AuditLogs_Category" ON "AuditLogs" ("Category");
                CREATE INDEX "IX_AuditLogs_CreatedAt" ON "AuditLogs" ("CreatedAt");
                CREATE INDEX "IX_AuditLogs_CustomerId" ON "AuditLogs" ("CustomerId");
                CREATE INDEX "IX_AuditLogs_EntityType_EntityId" ON "AuditLogs" ("EntityType", "EntityId");
                CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
                """);

            // FK'lari geri ekle
            migrationBuilder.AddForeignKey(
                name: "FK_AuditLogs_Customers_CustomerId",
                table: "AuditLogs",
                column: "CustomerId",
                principalTable: "Customers",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_AuditLogs_Users_UserId",
                table: "AuditLogs",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
