using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CallCenter.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddPlatformPushToken : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "PlatformPushTokens" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "PlatformUserId" integer NOT NULL,
                    "Token" text NOT NULL,
                    "Platform" text NOT NULL,
                    "DeviceId" text,
                    "IsActive" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone,
                    "LastUsedAt" timestamp with time zone,
                    CONSTRAINT "PK_PlatformPushTokens" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_PlatformPushTokens_PlatformUsers_PlatformUserId"
                        FOREIGN KEY ("PlatformUserId") REFERENCES "PlatformUsers" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_PlatformPushTokens_PlatformUserId"
                    ON "PlatformPushTokens" ("PlatformUserId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "PlatformPushTokens";""");
        }
    }
}
